#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#assign var 

filepath=$1
ip=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$filepath" "$username@$ip:~/"

#check status

if [ $? -eq 0 ]
then 
		echo "File Successfully Transfered"
else 
		echo "File not uploaded"
fi
