#!/usr/bin/env bash

i=1
while [ $i -le 20 ]
do
    case $i in
        4)
            echo "4"
            echo "Bad luck from China"
            ;;
        9)
            echo "9"
            echo "Bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "Bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac
    i=$((i + 1))
done